2022-06-30 01:11:56,000 ERROR: Exception on /index [GET] [in d:\github\microblog2\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "d:\github\microblog2\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\github\microblog2\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\github\microblog2\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\github\microblog2\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "d:\github\microblog2\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\microblog2\app\routes.py", line 29, in index
    return render_template("index.html", title='Home Page',form=form,
  File "d:\github\microblog2\lib\site-packages\flask\templating.py", line 148, in render_template
    return _render(
  File "d:\github\microblog2\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "d:\github\microblog2\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "d:\github\microblog2\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\microblog2\app\templates\index.html", line 1, in top-level template code
    {%extends "base.html" %}
  File "D:\microblog2\app\templates\base.html", line 29, in top-level template code
    {% block content %}{% endblock %}
  File "D:\microblog2\app\templates\index.html", line 22, in block 'content'
    {{ post.author.username }} says: <b>{{ post.body }}</b>
  File "d:\github\microblog2\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'post' is undefined
2022-06-30 01:11:56,989 ERROR: Exception on /index [GET] [in d:\github\microblog2\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "d:\github\microblog2\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\github\microblog2\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\github\microblog2\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\github\microblog2\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "d:\github\microblog2\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\microblog2\app\routes.py", line 29, in index
    return render_template("index.html", title='Home Page',form=form,
  File "d:\github\microblog2\lib\site-packages\flask\templating.py", line 148, in render_template
    return _render(
  File "d:\github\microblog2\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "d:\github\microblog2\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "d:\github\microblog2\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\microblog2\app\templates\index.html", line 1, in top-level template code
    {%extends "base.html" %}
  File "D:\microblog2\app\templates\base.html", line 29, in top-level template code
    {% block content %}{% endblock %}
  File "D:\microblog2\app\templates\index.html", line 22, in block 'content'
    {{ post.author.username }} says: <b>{{ post.body }}</b>
  File "d:\github\microblog2\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'post' is undefined
2022-06-30 01:12:26,373 INFO: Microblog Startup [in D:\microblog2\app\__init__.py:43]
2022-06-30 01:35:47,044 INFO: Microblog Startup [in D:\microblog2\app\__init__.py:43]
2022-07-02 00:56:49,203 INFO: Microblog Startup [in D:\microblog2\app\__init__.py:43]
2022-07-02 01:00:35,782 INFO: Microblog Startup [in D:\microblog2\app\__init__.py:43]
2022-07-02 01:13:07,264 INFO: Microblog Startup [in D:\microblog2\app\__init__.py:43]
2022-07-02 01:13:09,760 ERROR: Exception on / [GET] [in d:\github\microblog2\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "d:\github\microblog2\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\github\microblog2\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\github\microblog2\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\github\microblog2\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "d:\github\microblog2\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\microblog2\app\routes.py", line 36, in index
    return render_template("index.html", title='Home Page',form=form,
  File "d:\github\microblog2\lib\site-packages\flask\templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "d:\github\microblog2\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "d:\github\microblog2\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "d:\github\microblog2\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "d:\github\microblog2\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "d:\github\microblog2\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "d:\github\microblog2\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\microblog2\app\templates\index.html", line 22, in template
    {% endif %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endif'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2022-07-02 01:15:03,528 INFO: Microblog Startup [in D:\microblog2\app\__init__.py:43]
2022-07-02 01:34:03,097 INFO: Microblog Startup [in D:\microblog2\app\__init__.py:43]
2022-07-04 02:20:03,475 INFO: Microblog Startup [in D:\microblog2\app\__init__.py:46]
2022-07-05 00:44:40,641 INFO: Microblog Startup [in D:\microblog2\app\__init__.py:46]
2022-07-06 20:45:20,532 INFO: Microblog Startup [in D:\microblog2\app\__init__.py:46]
2022-07-06 21:39:56,838 INFO: Microblog Startup [in D:\microblog2\app\__init__.py:46]
2022-07-06 22:03:31,625 INFO: Microblog Startup [in D:\microblog2\app\__init__.py:46]
2022-07-06 22:05:07,252 INFO: Microblog Startup [in D:\microblog2\app\__init__.py:46]
2022-07-06 22:05:32,268 INFO: Microblog Startup [in D:\microblog2\app\__init__.py:46]
2022-07-06 22:08:02,602 INFO: Microblog Startup [in D:\microblog2\app\__init__.py:46]
2022-07-06 22:08:45,516 INFO: Microblog Startup [in D:\microblog2\app\__init__.py:46]
2022-07-06 22:27:48,147 INFO: Microblog Startup [in D:\microblog2\app\__init__.py:46]
2022-07-08 01:07:02,663 INFO: Microblog Startup [in D:\microblog2\app\__init__.py:46]
2022-07-15 02:31:09,841 INFO: Microblog Startup [in D:\microblog2\app\__init__.py:46]
2022-07-20 00:55:41,265 INFO: Microblog Startup [in D:\microblog2\app\__init__.py:46]
